### ISSUE TITLE
Numbers as strings (with commas)

### ISSUE THREAD

**Issue by dash-** [thirteen23/esi-test#1]
https://github.com/thirteen23/esi-test/blob/9fe99dd3a23d2c5c6c031e2ff3bbdf9186233d32/test-app/src/App.js#L17

Seems unlikely the data would be preformatted with numbers as strings (with commas in it already)...

**Comment by dash-** [comment]
I've been out of the loop though, so if this was provided sample data then it could very well be right - I'd just double check.  Seems like a weird choice, that's all.

**Comment by karelwgonzalez** [comment]
@dash- This is the way the data was provided to me. Ideally it would be passed in as a number instead of a formatted string though.

**Comment by dash-** [comment]
Yeah - well nothing surprises me these days.  There could be a good reason for it.  My biggest fear is that the person that provided it didn't think it through and will end up changing it later.  I'll try to validate that it's definitely right next week.  And then figure out if there's some logic behind the odd choice - because yeah it's not just weird, it seems pretty sub-optimal having to convert it back to a number to work with it.

Thanks @karelwgonzalez !
